### ISSUE TITLE
plugin does not seem to work in zeek 3.x

### ISSUE THREAD

**Issue by mmguero** [corelight/bro-xor-exe-plugin#2]
Steps I've done to reproduce:

1. compile [zeek v3.0.5](https://github.com/zeek/zeek/releases/tag/v3.0.5) from source (my installation is Debian 10: here are [my steps to compile zeek](https://github.com/idaholab/Malcolm/blob/master/Dockerfiles/zeek.Dockerfile#L42..L53), but I don't think it's specific to my configuration)
2. install bro-xor-exe-plugin with zkg (here's [my script](https://github.com/idaholab/Malcolm/blob/master/shared/bin/zeek_install_plugins.sh#L76) where I'm installing my plugins, but again I don't think it's specific to my setup)
3. have the default [local.zeek](https://github.com/zeek/zeek/blob/master/scripts/site/local.zeek)
4. check `zeek -N`:
```
# zeek -N local | grep XOR
Corelight::PE_XOR - Plugin to detect and decrypt XOR-encrypted EXEs (dynamic, version 0.1.0)
```
5. run zeek on the [trace pcap](https://github.com/corelight/bro-xor-exe-plugin/blob/master/tests/Traces/2015-04-09-Nuclear-EK-traffic.pcap)
```
# zeek -C -r /host/2015-04-09-Nuclear-EK-traffic.pcap local policy/misc/loaded-scripts
WARNING: No Site::local_nets have been defined.  It's usually a good idea to define your local networks.
```

**RESULTS:**

- the XOR notice does not exist in `notice.log`
- the `pe.log` file does not exist, nor does the exe file show up in `files.log`
- the plugin did seem to load properly:
```
# grep -i xor loaded_scripts.log 
/opt/zeek/lib/zeek/plugins/packages/bro-xor-exe-plugin/lib/bif/__load__.zeek
  /opt/zeek/lib/zeek/plugins/packages/bro-xor-exe-plugin/lib/bif/pe_xor.bif.zeek
```

I'm happy to provide any more information about my configuration, if that would help, to pinpoint the issue.

**Comment by sethhall** [comment]
It doesn't look like the script actually loaded.  What you showed loading was just the bif support.

**Comment by mmguero** [comment]
lol, oof, okay. hmmmm, now looking at my plugins directory, i'm seeing:

```
# find / -iname "*xor*"
...
/opt/zeek/lib/zeek/plugins/packages/bro-xor-exe-plugin
/opt/zeek/lib/zeek/plugins/packages/bro-xor-exe-plugin/lib/bif/pe_xor.bif.zeek
/opt/zeek/lib/zeek/plugins/packages/bro-xor-exe-plugin/lib/Corelight-PE_XOR.linux-x86_64.so
/opt/zeek/lib/zeek/plugins/packages/bro-xor-exe-plugin/pe_xor.bif.cc
/opt/zeek/lib/zeek/plugins/packages/bro-xor-exe-plugin/pe_xor.bif.register.cc
/opt/zeek/lib/zeek/plugins/packages/bro-xor-exe-plugin/dist/Corelight_PE_XOR-0.1.tar.gz
/opt/zeek/lib/zeek/plugins/packages/bro-xor-exe-plugin/pe_xor.bif.h
/opt/zeek/lib/zeek/plugins/packages/bro-xor-exe-plugin/pe_xor.bif.init.cc
/opt/zeek/lib/zeek/plugins/packages/bro-xor-exe-plugin/Corelight_PE_XOR.tgz
```

But not the script itself, which lines up with what you're saying. So really it's the installation of the script that went wrong in my system, rather than the script itself. I'll see if I install it manually (vs using zkg) if it works better.

**Comment by mmguero** [comment]
So yeah, I did the zkg install and didn't end up with the script, just the bif stuff. Copying the script over manually and things did show up. So I'll figure out why my installation's borked.

Closing as the bug's invalid.

**Comment by mmguero** [comment]
FWIW it did install the scripts correctly when I do the `configure`, `make`, `make install` method and specify the `bro-dist` and `install-root` paths.
